#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso deepLungMPPICTurbulenceModels

wclean
#wclean MPPICFoam
#wclean DPMDyMFoam
#wclean DPMDyMFoam/MPPICDyMFoam

#------------------------------------------------------------------------------
